### ISSUE TITLE
Travis failure on CCPi-Framework

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#360]
https://travis-ci.org/github/CCPPETMR/SIRF-SuperBuild/jobs/663096871#L1643
```
CMake Error: The source directory "/opt/SIRF-SuperBuild/sources/CCPi-Framework" does not appear to contain CMakeLists.txt.
```

There's also
https://travis-ci.org/github/CCPPETMR/SIRF-SuperBuild/jobs/663096871#L1516
```
CMake Warning at SuperBuild/External_CCPi-Regularisation-Toolkit.cmake:57 (message):
  CIL_VERSION
```
which implies that `CIL_VERSION` is empty in `SuperBuild/External_CCPi-Regularisation-Toolkit.cmake`, but that might be alright, in which case the warning needs to be deleted.

Possibly this error is another case of a broken update in CCPi code, #347

**Comment by rijobro** [comment]
It seems that they put in a `CMakeLists.txt` between the last release `19.10` and now. Perhaps that's why they were just doing copies before, so my PR #359 will have broken it for older versions. Is that right @paskino ?

As it is, it seems to be broken one way or another. Either we use the old method and then the library won't be compiled so it fails. Or we use the PR I put in yesterday, in which the last stable release will fail as there is no `CMakeLists.txt`.

Would it be possible to do another release and then we could reference that?

**Comment by rijobro** [comment]
If travis goes green (it did for the PR), then #362 should have fixed this.
